kind: pipeline
type: docker
name: madness

steps:
  - name: dco
    image: algernon/drone-plugin-dco
    depends_on: [ clone ]

  - name: signature-check
    image: algernon/drone-plugin-signature-check
    keys: [ 10E65DC045EABEFCC5193A26AC1E90BAC433F68F ]
    when:
      event: tag
    depends_on: [ clone ]

  - name: cache-restore
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./local-m2
    depends_on: [ clone ]

  - name: dependencies
    image: clojure:lein
    commands:
      - lein deps
    depends_on: [ cache-restore ]

  - name: build-css
    image: clojure:lein
    commands:
      - lein garden once
    depends_on: [ dependencies ]

  - name: build-html
    image: clojure:lein
    commands:
      - apt-get update -qq
      - apt-get -qq -y install python-pygments
      - lein run -m madness.core
    depends_on: [ dependencies ]

  - name: cache-rebuild
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./local-m2
    depends_on: [ build-html ]

  - name: deploy-public
    image: appleboy/drone-scp
    settings:
      host: bedlam.madhouse-project.org
      username: drone-bedlam
      port: 242
      source: public/
      target: public/
      strip_components: 1
      rm: true
      key:
        from_secret: ssh_key
    depends_on: [ build-html ]

  - name: deploy-assets
    image: appleboy/drone-scp
    settings:
      host: bedlam.madhouse-project.org
      username: drone-bedlam
      port: 242
      source: resources/assets
      target: public/assets/
      strip_components: 2
      rm: true
      key:
        from_secret: ssh_key
    depends_on: [ deploy-public ]

  - name: deploy-pwa
    image: appleboy/drone-scp
    settings:
      host: bedlam.madhouse-project.org
      username: drone-bedlam
      port: 242
      source: resources/pwa
      target: public/pwa/
      strip_components: 2
      rm: true
      key:
        from_secret: ssh_key
    depends_on: [ deploy-public ]

volumes:
  - name: cache
    host:
      path: /tmp/cache/madness
